name: test

on:
  pull_request:
    types:
      - closed
#   branches:
#     - 'release/v*.*.*'

jobs:
  test:
    name: test trigger workflow when release/v*.*.* is merged
    if: github.event.action == 'closed' && github.event.pull_request.merged && startsWith(github.ref_name, 'release/v')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo 'Hello!'
